resources:
  - name: resource_2_new_r
    type: GitRepo
    configuration:
      gitProvider: test
      path:  seekhJaunga/Ekart
      buildOn:
         releaseCreate: true
         commit: false

pipelines:
  - name: single_test_new_new_new
    configuration:
      environmentVariables:
        readOnly:
          env2: "test_p2"
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          timeoutSeconds: 5
          inputResources:
            - name: resource_2_new_r
        execution:
          onExecute:
            - echo $resource_2_new_r_path
